### ISSUE TITLE
request instead of $request

### ISSUE THREAD

**Issue by thsteinmetz** [urlhum/UrlHum#1]
https://github.com/urlhum/UrlHum/blob/bab87272f8242466e9b5137aeebc0454b93e510d/app/Http/Controllers/UrlController.php#L71

**Comment by optiroot** [comment]
Thank your for opening the issue!
Here we are getting the url of the "server" website, so I thought that for more clearness would have been better to not to use the variable $request as it is injected for the real request and so to use the global helper.

If you know a better reason to edit that line of code I am willing to update it without problems! 
Meanwhile I wait for other opinions too!

**Comment by thsteinmetz** [comment]
Ah, understood!
