### ISSUE TITLE
No public forder

### ISSUE THREAD

**Issue by CarlosCasasnova** [urlhum/UrlHum#2]
To begin the installation, login into your server and configure Apache or Nginx to work with the new project.
Remember: the root directory must point to app/public

404 Not Found
nginx/1.14.0 (Ubuntu)

app$ ls
Analytics.php  Console  DeletedUrls.php  Exceptions  Http  IpAnonymizer.php  Providers  Rules  Services  Settings.php  Url.php  User.php  ViewUrl.php

**Comment by optiroot** [comment]
Hello Carlos, thank you for creating the issue.

Did you run the installation after creating the Apache / Nginx configuration file?
The **public** folder will create after the **composer install** command.

**Comment by optiroot** [comment]
Sorry. I've found the error. It was a distraction error. The correct folder is **public**, not **app/public**.
I'm going to correct the documentation.

**Comment by CarlosCasasnova** [comment]
thank you very much for the quick response I followed all the steps but I still have problem in the configuration nginx you would have an example -- installation was passed without any error

**Comment by optiroot** [comment]
I updated the documentation with an [Nginx sample configuration file](https://urlhum.readme.io/docs/nginx-configuration-sample). Please remember that sample file is for Ubuntu 18.04 and php-fpm7.2 
If you have a different version of one or the other you need to edit the configuration file.

Do you have any error log so I can try to understand the problem?

**Comment by CarlosCasasnova** [comment]
Thanks, it works!! 
there was no error no log -was a problem in nginx configuration in the php part
:)
