### ISSUE TITLE
[BUG] Existence of @honeypot 

### ISSUE THREAD

**Issue by iamchuchat** [urlhum/UrlHum#25]
![image](https://user-images.githubusercontent.com/47782704/57618764-ddf79a00-75b6-11e9-8ce6-6795e96fcb21.png)
@honeypot is showing in the front-end.

**Comment by optiroot** [comment]
Please provide more details, following the [Bug report template](https://github.com/urlhum/UrlHum/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
Thank you!

**Comment by optiroot** [comment]
I'm closing the issue because I can't replicate it and need more details.
You can reopen it if you need to.
Thanks!

**Comment by IAmBeginner** [comment]
I think I messed up with some of the codes and ended up getting the error. I couldn't track the error I made so I decided to reinstall the script and that fixes the error. Thanks @Optiroot! I am looking forward for the updates of this cool project of yours. :))

**Comment by optiroot** [comment]
No worries! 
I'm happy you solved, anyway.
Thanks!
