### ISSUE TITLE
Using UrlHum with Postgres results in internal server errors

### ISSUE THREAD

**Issue by davidolrik** [urlhum/UrlHum#29]
When using PostgreSQL as database, all pages that use queries with `IFNULL` results in internal an server error as this is a MySQL only function.

As a temporary workaround I have changed it to `COALESCE` locally.

I suggest moving this logic into the application and handle the possibility of null in code using something like `$value ?? "default"`.

**Comment by optiroot** [comment]
Hello!
Thank you for opening the issue.
Yes, actually UrlHum doesn't work with **PostgreSQL**, but it is planned. As you can see in the [docs](https://urlhum.readme.io/docs/getting-started) it is stated that UrlHum has been tested with *mySQL* only.
I will update the project soon to be able to work with PostgreSQL.
Thanks!

**Comment by optiroot** [comment]
Fixed this! Also, I managed to clean up some code using Laravel Relationships. 
Now the project is cleaner and works perfectly with PostgreSQL too!
