### ISSUE TITLE
API access with API key

### ISSUE THREAD

**Issue by davidolrik** [urlhum/UrlHum#30]
Each user should have the ability to get an api key, which they can use to shorten urls with using a single`GET` request.

This will allow us to integrate UrlHum with a lot of apps, e.g. [DropShare](https://dropshare.zendesk.com/hc/en-us/articles/201268771-How-to-set-up-a-custom-URL-shortener) - See the paragraph with "Compatible (open source) URL shorteners"

**Comment by optiroot** [comment]
Thanks for creating the issue!
Yes, it is planned to create APIs (not only for Short URLs creation) so just give UrlHum some time more to grow. You will see them soon! 😄

**Comment by optiroot** [comment]
APIs are created, but they need improvement. We will improve them over time.
Closing this.
