### ISSUE TITLE
[Request] Add a link to the details page for URL entries on the dashboard

### ISSUE THREAD

**Issue by erdmenchen** [urlhum/UrlHum#36]
From using the hosted Demo version:
When viewing the dashboard, let me click on an entry in the "Latest URLs" table, to navigate to the analytics detail page of this URL.

There is currently no way to navigate to the details analytics page of an entry in the dashboard.
I have to manually copy the short URL and add the "+" sign in the browser address field.

**Comment by optiroot** [comment]
Working on this.
