### ISSUE TITLE
[Request] On the analytics page of a URL add a table with all request records sorted by time

### ISSUE THREAD

**Issue by erdmenchen** [urlhum/UrlHum#37]
From using the hosted Demo version:
When viewing the detailed analytics page for a short URL, there is currently no time insight about the usage of a shortened URL e.g. when a short URL was clicked the first time, after creation.

At least, I would like to see a table with the last X records of requests, showing me the exact time of the URL request.

My use case would be:
I have a resource and I want to share it with someone and I want to see, if he opened the link after sharing and when.
So I create a shortened URL on urlhum and am sending this URL in order to see, if and when the other party opened the resource.

**Comment by optiroot** [comment]
This is a great idea. But because UrlHum is privacy-focused, the analytics page will only show the latest clicks / real clicks, the time of the click and if available the referer; nothing more: because we don't collect users details to make them recognizable.

I will work on this. Thanks!
