### ISSUE TITLE
[Bug] When viewing the settings page on a narrow window, all setting controls are cut off

### ISSUE THREAD

**Issue by erdmenchen** [urlhum/UrlHum#38]
**Describe the bug**
When viewing the settings page on the current demo instance in a narrow window (<1290px width) all setting controls are cut off and only after scrolling to the bottom I am able to scroll the container to the right

**To Reproduce**
1. Go to the settings view 
2. Resize the window to a width <1290 px
3. All switches and settings controls are cut of and not visible

**Expected behavior**
Improve the responsive design to not cut off control elements.

**Actual behavoir**
Controls are cut off.

**Screenshots**
![image](https://user-images.githubusercontent.com/6791096/58011351-5815aa80-7af2-11e9-8b61-e433c53398dd.png)
![image](https://user-images.githubusercontent.com/6791096/58011373-649a0300-7af2-11e9-9db2-60cba2c4f1d8.png)

**Comment by optiroot** [comment]
Thank you for reporting this. I'm working on a fix for it.

This is a bug.
