### ISSUE TITLE
[Request] Clarify the difference between clicks and real clicks and views

### ISSUE THREAD

**Issue by erdmenchen** [urlhum/UrlHum#39]
Its unclear to me as a user, what the difference is between clicks and real clicks, and also what is the difference between clicks and views.

Make this clearer, either by documenting it or by reducing complexity and only talk about one kind of interactions:
Since this project is only counting url requests and is not a usage analytics tool inside of a website (e.g. google analytics) with custom javascript, only talks about clicks and not views.

As a user I am confused about what is shown on the analytics page of a shortened URL.

**Comment by optiroot** [comment]
Hello @erdmenchen!
Thank you for opening this.
You're right saying that there is some confusion about clicks vs views. Actually they are the **same** thing. But we use *views* when we talk about *countries*, and we use *clicks* for all the rest.
If this is confusing (and now I'm thinking it is), I can change it to just *views* or just *clicks*.

I leave this issue open so I invite others to contribute by sending their opinion here, so we can choose either *clicks* or *views*.
Thank you!

**Comment by michaellindahl** [comment]
My vote is on clicks. This aligns with other URL shorteners like bit.ly and kutt.it

**Comment by michaellindahl** [comment]
@optiroot What is the difference between clicks and real clicks?

**Comment by realodix** [comment]
> You're right saying that there is some confusion about clicks vs views. Actually they are the **same** thing. But we use _views_ when we talk about _countries_, and we use _clicks_ for all the rest.

@optiroot what the difference is between clicks and real clicks?

**Comment by optiroot** [comment]
Actually, **clicks** are the same as **views** so, **real clicks** and **real views** are the same thing also.
The difference between "clicks" and "real clicks" is that real clicks evaluates for a single IP click in the last 24h hours. While, "clicks" is how many clicks in general the link had (for example if the same user clicks the link two times, we will have **2 clicks** but **1 real click**).

**Comment by erdmenchen** [comment]
Why not calling it *visitors* and *clicks*?

**Comment by optiroot** [comment]
I have an update on this.
Having checked other Url Shorteners, I came to the conclusion that between **clicks** and **views** it's better to use **clicks**. 
Soon I'll push a commit that changes everything related to this. 

Thanks you everyone!
