### ISSUE TITLE
Redirect Root Domain

### ISSUE THREAD

**Issue by GavinMcNabb** [urlhum/UrlHum#49]
Love it so far. Just wondering if there is a way to have the root of the shortened url redirect to another site, and have the admin panel under either a subdomain or sub folder.

**Comment by optiroot** [comment]
Hello! Sadly, UrlHum at the moment doesn't have this function. It might be implemented in future, though.
We need make the project more stable first.

I'm going to close the issue but feel free to reply if you have any other opinion on this or want to share more details.
Thanks! :)
