### ISSUE TITLE
Site has no design for me.

### ISSUE THREAD

**Issue by Azocki** [urlhum/UrlHum#50]
Hello, i installed successfully UrlHum on my webserver (Shared Hosting, HawkHost)
after installation i visited "myurl.com/UrlHum/public" and what i see is:
https://depressive.club/ZLe.png

i dont see any design or anything what could it be?

**Comment by Azocki** [comment]
i fixed it by moving all the files from public (css, js, svg) to public_html folder fixed it for me !

**Comment by Azocki** [comment]
next issue: i cant go to settings or make a url...

**Comment by Azocki** [comment]
https://depressive.club/DKs.png

**Comment by optiroot** [comment]
Hello, thank you for creating this issue.

UrlHum doesn't work in shard hosting at the moment, and you shouldn't visit the public folder, but the main root itself. You need to point the web server root to the **public** folder, but in your browser you must visit the website.
Also, UrlHum hasn't been tested to work in a subfolder, you need to use a subdomain or a domain to make it work.

Let me know if you need any other help! :)

**Comment by Azocki** [comment]
;( really come on

**Comment by Azocki** [comment]
https://lolcgteamwins.pw

**Comment by Azocki** [comment]
i have a domain

**Comment by Azocki** [comment]
i just wasted all my money on this hosting to try it out, all worked the install all worked easy but know its just a waste

**Comment by optiroot** [comment]
Closing this because we're solving the issue in UrlHum Telegram Group.

**Comment by Azocki** [comment]
ok
