### ISSUE TITLE
[Request] Redirect anyone who hits the domain to a different site 

### ISSUE THREAD

**Issue by austriker27** [urlhum/UrlHum#58]
It would be neat if you could setup a redirect so anyone who hits myurlhumdomain.com would be redirected to a site of our choosing. This would be in case any savy user sees the short url domain and tries to go to it. Also it would help keep my urlhum admin site even more secret.

Thanks!

**Comment by optiroot** [comment]
Thank you for creating this feature request!

This is a feature that can be done without problems. It is ongoing!
