### ISSUE TITLE
Got some errors when running docker-compose

### ISSUE THREAD

**Issue by MParvin** [urlhum/UrlHum#82]
I got these errors when running UrlHum with docker-compose :

`error: /usr/src/php/ext/php-gd does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlrpc xmlwriter xsl zend_test zip

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
ERROR: Service 'urlhum' failed to build: The command '/bin/sh -c apk add --no-cache composer && docker-php-ext-install mysqli pdo pdo_mysql php-gd' returned a non-zero code: 1
`
I add `gd` to end of docker-php-ext-install command then resolved:
`RUN apk add --no-cache composer && docker-php-ext-install mysqli pdo pdo_mysql gd`

After that got error about  'zlib'  and `libpng-dev` that required by 'virtual:world'.
Added `zlib-dev` and  `libpng-dev` to apk add resolved these errors.

`RUN apk add --no-cache composer zlib-dev libpng-dev`

Finally changes in line number 4 of Dockerfile to below line resolved my issue
`RUN apk add --no-cache composer zlib-dev libpng-dev && docker-php-ext-install mysqli pdo pdo_mysql gd`

**Comment by optiroot** [comment]
Hello,
thank you for taking the time to solve the problem. 

Could you make a Pull Request with your solution? Thanks.

**Comment by timhuangt** [comment]
Hello there,

I've PR with this to solve this problem: 

https://github.com/urlhum/UrlHum/pull/80

**Comment by Niggl1999** [comment]
Hi there,
first of all: Thanks for fixing the issue in the dockerfile :)
I tested the solution provided in the pr and everything worked as expected.

@optiroot could you merge @timhuangt's PR?

**Comment by timhuangt** [comment]
Since the PR https://github.com/urlhum/UrlHum/pull/80 is merged, this issue can be closed.
