### ISSUE TITLE
don't work urlhum help me

### ISSUE THREAD

**Issue by anka5307** [urlhum/UrlHum#92]
hi...

I have a web site urlhum  uploaded but don't work please help me ?

mail adress : anka5307@gmail.com 

web site :indirya.net

**Comment by optiroot** [comment]
Hello,

could you better explain the problems you're encountering so we can help you?

**Comment by anka5307** [comment]
urlhum script don't working  web site run now  loking you   indirya.net

**Comment by optiroot** [comment]
You need to point the root directory in your webserver config file (Virtualhost) to the /public directory.

Also, I recommend to disable Apache file indexing to avoid exposure of server files.

**Comment by anka5307** [comment]
<a href="Your Website Link" rel="dofollow">Your Anchor Text</a>
